import type {
  CaptacaoPerez,
  ContratoPerez,
  ImovelPerez,
  LancamentoPerez,
  ManutencaoPerez,
  PessoaPerez,
} from "./tipos";

const foto = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=82`;

const GALERIAS = {
  apartamento: [
    foto("photo-1600607687939-ce8a6c25118c"),
    foto("photo-1600566753086-00f18fb6b3ea"),
    foto("photo-1600210492486-724fe5c67fb0"),
  ],
  casa: [
    foto("photo-1600585154340-be6161a56a0c"),
    foto("photo-1600047509807-ba8f99d2cdde"),
    foto("photo-1494526585095-c41746248156"),
  ],
  comercial: [
    foto("photo-1486406146926-c627a92ad1ab"),
    foto("photo-1497366754035-f200968a6e72"),
    foto("photo-1524758631624-e2822e304c36"),
  ],
  lancamento: [
    foto("photo-1545324418-cc1a3fa10c00"),
    foto("photo-1600566752355-35792bedcfea"),
    foto("photo-1600566753190-17f0baa2a6c3"),
  ],
} as const;

const descricao =
  "Um imóvel selecionado pela Perez para unir localização, conforto e uma experiência de moradia segura. Ambientes bem distribuídos, acabamento contemporâneo e atendimento próximo em todas as etapas.";

export const IMOVEIS_PEREZ: ImovelPerez[] = [
  {
    id: "imovel-01",
    codigo: "PZ-1001",
    titulo: "Apartamento panorâmico no Maison Heritage",
    finalidade: "venda",
    tipo: "apartamento",
    bairro: "Gleba Palhano",
    cidade: "Londrina",
    enderecoAproximado: "Rua João Wyclif, Gleba Palhano",
    preco: 1_280_000,
    condominio: 980,
    area: 156,
    quartos: 3,
    suites: 2,
    banheiros: 4,
    vagas: 2,
    descricao,
    comodidades: ["Varanda gourmet", "Piscina", "Academia", "Portaria 24 horas"],
    imagens: [...GALERIAS.apartamento],
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-01",
    corretor: "Camila Nogueira",
  },
  {
    id: "imovel-02",
    codigo: "PZ-1002",
    titulo: "Apartamento mobiliado próximo ao Lago Igapó",
    finalidade: "locacao",
    tipo: "apartamento",
    bairro: "Gleba Palhano",
    cidade: "Londrina",
    enderecoAproximado: "Avenida Ayrton Senna, Gleba Palhano",
    preco: 4_800,
    condominio: 760,
    area: 118,
    quartos: 3,
    suites: 1,
    banheiros: 3,
    vagas: 2,
    descricao,
    comodidades: ["Mobiliado", "Sacada", "Coworking", "Brinquedoteca"],
    imagens: [...GALERIAS.apartamento].reverse(),
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-03",
    corretor: "Renato Martins",
  },
  {
    id: "imovel-03",
    codigo: "PZ-1003",
    titulo: "Casa contemporânea com jardim e piscina",
    finalidade: "venda",
    tipo: "casa",
    bairro: "Terra Bonita",
    cidade: "Londrina",
    enderecoAproximado: "Rua das Acácias, Terra Bonita",
    preco: 1_490_000,
    condominio: 520,
    area: 284,
    quartos: 4,
    suites: 3,
    banheiros: 5,
    vagas: 4,
    descricao,
    comodidades: ["Piscina", "Espaço gourmet", "Escritório", "Energia solar"],
    imagens: [...GALERIAS.casa],
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-05",
    corretor: "Camila Nogueira",
  },
  {
    id: "imovel-04",
    codigo: "PZ-1004",
    titulo: "Conjunto comercial renovado no Centro",
    finalidade: "locacao",
    tipo: "comercial",
    bairro: "Centro",
    cidade: "Londrina",
    enderecoAproximado: "Avenida Paraná, Centro",
    preco: 3_200,
    condominio: 640,
    area: 82,
    quartos: 0,
    suites: 0,
    banheiros: 2,
    vagas: 1,
    descricao,
    comodidades: ["Recepção", "Ar-condicionado", "Elevador", "Portaria"],
    imagens: [...GALERIAS.comercial],
    destaque: false,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-07",
    corretor: "Renato Martins",
  },
  {
    id: "imovel-05",
    codigo: "PZ-1005",
    titulo: "Casa acolhedora em rua tranquila",
    finalidade: "venda",
    tipo: "casa",
    bairro: "Jardim Quebec",
    cidade: "Londrina",
    enderecoAproximado: "Rua Professor Samuel Moura, Jardim Quebec",
    preco: 980_000,
    condominio: null,
    area: 224,
    quartos: 3,
    suites: 1,
    banheiros: 3,
    vagas: 3,
    descricao,
    comodidades: ["Quintal", "Churrasqueira", "Sala de TV", "Despensa"],
    imagens: [...GALERIAS.casa].reverse(),
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-01",
    corretor: "Lívia Toledo",
  },
  {
    id: "imovel-06",
    codigo: "PZ-1006",
    titulo: "Apartamento iluminado na Higienópolis",
    finalidade: "locacao",
    tipo: "apartamento",
    bairro: "Higienópolis",
    cidade: "Londrina",
    enderecoAproximado: "Rua Piauí, Higienópolis",
    preco: 2_650,
    condominio: 490,
    area: 86,
    quartos: 2,
    suites: 1,
    banheiros: 2,
    vagas: 1,
    descricao,
    comodidades: ["Sacada", "Armários", "Salão de festas", "Bicicletário"],
    imagens: [...GALERIAS.apartamento],
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-03",
    corretor: "Lívia Toledo",
  },
  {
    id: "imovel-07",
    codigo: "PZ-1007",
    titulo: "Apartamento moderno no Aurora",
    finalidade: "venda",
    tipo: "apartamento",
    bairro: "Aurora",
    cidade: "Londrina",
    enderecoAproximado: "Rua Bélgica, Aurora",
    preco: 720_000,
    condominio: 580,
    area: 94,
    quartos: 2,
    suites: 1,
    banheiros: 2,
    vagas: 2,
    descricao,
    comodidades: ["Varanda", "Academia", "Pet place", "Piscina"],
    imagens: [...GALERIAS.lancamento],
    destaque: false,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-05",
    corretor: "Camila Nogueira",
  },
  {
    id: "imovel-08",
    codigo: "PZ-1008",
    titulo: "Sobrado amplo em condomínio fechado",
    finalidade: "locacao",
    tipo: "casa",
    bairro: "Terra Bonita",
    cidade: "Londrina",
    enderecoAproximado: "Avenida Harry Prochet, Terra Bonita",
    preco: 6_900,
    condominio: 680,
    area: 310,
    quartos: 4,
    suites: 3,
    banheiros: 5,
    vagas: 4,
    descricao,
    comodidades: ["Condomínio fechado", "Piscina", "Lareira", "Jardim"],
    imagens: [...GALERIAS.casa],
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-05",
    corretor: "Renato Martins",
  },
  {
    id: "imovel-09",
    codigo: "PZ-1009",
    titulo: "Sala comercial com vista para a cidade",
    finalidade: "venda",
    tipo: "comercial",
    bairro: "Centro",
    cidade: "Londrina",
    enderecoAproximado: "Rua Pernambuco, Centro",
    preco: 640_000,
    condominio: 720,
    area: 104,
    quartos: 0,
    suites: 0,
    banheiros: 2,
    vagas: 2,
    descricao,
    comodidades: ["Recepção", "Duas salas", "Copa", "Gerador"],
    imagens: [...GALERIAS.comercial].reverse(),
    destaque: false,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-07",
    corretor: "Lívia Toledo",
  },
  {
    id: "imovel-10",
    codigo: "PZ-1010",
    titulo: "Casa funcional perto da Avenida Maringá",
    finalidade: "locacao",
    tipo: "casa",
    bairro: "Jardim Quebec",
    cidade: "Londrina",
    enderecoAproximado: "Rua Humaitá, Jardim Quebec",
    preco: 3_900,
    condominio: null,
    area: 196,
    quartos: 3,
    suites: 1,
    banheiros: 3,
    vagas: 2,
    descricao,
    comodidades: ["Edícula", "Quintal", "Armários", "Área de serviço"],
    imagens: [...GALERIAS.casa].reverse(),
    destaque: false,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-07",
    corretor: "Camila Nogueira",
  },
  {
    id: "imovel-11",
    codigo: "PZ-1011",
    titulo: "Lançamento Vista Igapó Signature",
    finalidade: "lancamento",
    tipo: "apartamento",
    bairro: "Gleba Palhano",
    cidade: "Londrina",
    enderecoAproximado: "Avenida Madre Leônia Milito, Gleba Palhano",
    preco: 1_650_000,
    condominio: null,
    area: 182,
    quartos: 4,
    suites: 3,
    banheiros: 5,
    vagas: 3,
    descricao,
    comodidades: ["Sky lounge", "Piscina coberta", "Quadra", "Delivery room"],
    imagens: [...GALERIAS.lancamento],
    destaque: true,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-01",
    corretor: "Renato Martins",
  },
  {
    id: "imovel-12",
    codigo: "PZ-1012",
    titulo: "Lançamento compacto no Aurora",
    finalidade: "lancamento",
    tipo: "apartamento",
    bairro: "Aurora",
    cidade: "Londrina",
    enderecoAproximado: "Avenida Adhemar Pereira de Barros, Aurora",
    preco: 590_000,
    condominio: null,
    area: 76,
    quartos: 2,
    suites: 1,
    banheiros: 2,
    vagas: 1,
    descricao,
    comodidades: ["Coworking", "Lavanderia", "Piscina", "Espaço gourmet"],
    imagens: [...GALERIAS.lancamento].reverse(),
    destaque: false,
    statusPublicacao: "publicado",
    proprietarioId: "pessoa-03",
    corretor: "Lívia Toledo",
  },
];

export const PESSOAS_PEREZ: PessoaPerez[] = [
  { id: "pessoa-01", nome: "Helena Siqueira", papeis: ["proprietario"], telefone: "(43) 99931-2040", email: "helena@exemplo.com", imoveisIds: ["imovel-01", "imovel-05", "imovel-11"] },
  { id: "pessoa-02", nome: "Carlos Eduardo Lima", papeis: ["lead", "cliente", "locatario"], telefone: "(43) 99812-4410", email: "carlos@exemplo.com", imoveisIds: [] },
  { id: "pessoa-03", nome: "Márcia Regina Alves", papeis: ["proprietario"], telefone: "(43) 99118-0082", email: "marcia@exemplo.com", imoveisIds: ["imovel-02", "imovel-06", "imovel-12"] },
  { id: "pessoa-04", nome: "Lucas Azevedo", papeis: ["locatario", "cliente"], telefone: "(43) 99662-9003", email: "lucas@exemplo.com", imoveisIds: [] },
  { id: "pessoa-05", nome: "Roberto Nakamura", papeis: ["proprietario"], telefone: "(43) 99881-4022", email: "roberto@exemplo.com", imoveisIds: ["imovel-03", "imovel-07", "imovel-08"] },
  { id: "pessoa-06", nome: "Ana Paula Freitas", papeis: ["locatario", "cliente"], telefone: "(43) 99204-6621", email: "ana.paula@exemplo.com", imoveisIds: [] },
  { id: "pessoa-07", nome: "Fernanda Queiroz", papeis: ["proprietario"], telefone: "(43) 99948-7802", email: "fernanda@exemplo.com", imoveisIds: ["imovel-04", "imovel-09", "imovel-10"] },
  { id: "pessoa-08", nome: "Marcos Oliveira", papeis: ["locatario", "cliente"], telefone: "(43) 99776-1830", email: "marcos@exemplo.com", imoveisIds: [] },
];

export const CONTRATOS_PEREZ: ContratoPerez[] = [
  { id: "contrato-01", imovelId: "imovel-02", proprietarioId: "pessoa-03", locatarioId: "pessoa-04", inicio: "2025-02-10", fim: "2027-02-09", proximoReajuste: "2027-02-10", valor: 4_800, status: "ativo" },
  { id: "contrato-02", imovelId: "imovel-06", proprietarioId: "pessoa-03", locatarioId: "pessoa-06", inicio: "2025-09-01", fim: "2027-08-31", proximoReajuste: "2026-09-01", valor: 2_650, status: "ativo" },
  { id: "contrato-03", imovelId: "imovel-08", proprietarioId: "pessoa-05", locatarioId: "pessoa-08", inicio: "2024-09-15", fim: "2026-09-14", proximoReajuste: "2026-09-15", valor: 6_900, status: "atencao" },
  { id: "contrato-04", imovelId: "imovel-10", proprietarioId: "pessoa-07", locatarioId: "pessoa-02", inicio: "2026-04-01", fim: "2028-03-31", proximoReajuste: "2027-04-01", valor: 3_900, status: "ativo" },
];

export const MANUTENCOES_PEREZ: ManutencaoPerez[] = [
  { id: "manutencao-01", imovelId: "imovel-08", solicitanteId: "pessoa-08", titulo: "Vazamento no banheiro da suíte", descricao: "Registro apresenta vazamento contínuo.", prioridade: "urgente", status: "aberta", prestador: "HidroLondrina", prazo: "2026-08-05" },
  { id: "manutencao-02", imovelId: "imovel-06", solicitanteId: "pessoa-06", titulo: "Revisão do interfone", descricao: "Interfone sem áudio na unidade.", prioridade: "alta", status: "em_andamento", prestador: "Conecta Serviços", prazo: "2026-08-07" },
  { id: "manutencao-03", imovelId: "imovel-02", solicitanteId: "pessoa-04", titulo: "Ajuste em porta de armário", descricao: "Porta desalinhada na cozinha.", prioridade: "normal", status: "aberta", prestador: null, prazo: "2026-08-12" },
  { id: "manutencao-04", imovelId: "imovel-10", solicitanteId: "pessoa-02", titulo: "Limpeza de calha", descricao: "Revisão preventiva antes do período de chuvas.", prioridade: "normal", status: "concluida", prestador: "Casa Certa", prazo: "2026-07-28" },
  { id: "manutencao-05", imovelId: "imovel-02", solicitanteId: "pessoa-04", titulo: "Tomada da sala", descricao: "Tomada apresenta mau contato.", prioridade: "alta", status: "concluida", prestador: "Volts Elétrica", prazo: "2026-07-22" },
];

export const LANCAMENTOS_PEREZ: LancamentoPerez[] = [
  { id: "lancamento-01", contratoId: "contrato-01", tipo: "recebimento", descricao: "Aluguel agosto", valor: 4_800, vencimento: "2026-08-10", status: "previsto" },
  { id: "lancamento-02", contratoId: "contrato-01", tipo: "repasse", descricao: "Repasse agosto", valor: 4_320, vencimento: "2026-08-13", status: "previsto" },
  { id: "lancamento-03", contratoId: "contrato-02", tipo: "recebimento", descricao: "Aluguel agosto", valor: 2_650, vencimento: "2026-08-08", status: "previsto" },
  { id: "lancamento-04", contratoId: "contrato-02", tipo: "repasse", descricao: "Repasse agosto", valor: 2_385, vencimento: "2026-08-12", status: "previsto" },
  { id: "lancamento-05", contratoId: "contrato-03", tipo: "recebimento", descricao: "Aluguel julho", valor: 6_900, vencimento: "2026-07-15", status: "pendente" },
  { id: "lancamento-06", contratoId: "contrato-03", tipo: "repasse", descricao: "Repasse condicionado", valor: 6_210, vencimento: "2026-07-18", status: "pendente" },
  { id: "lancamento-07", contratoId: "contrato-04", tipo: "recebimento", descricao: "Aluguel julho", valor: 3_900, vencimento: "2026-07-10", status: "realizado" },
  { id: "lancamento-08", contratoId: "contrato-04", tipo: "repasse", descricao: "Repasse julho", valor: 3_510, vencimento: "2026-07-13", status: "realizado" },
];

export const CAPTACOES_PEREZ: CaptacaoPerez[] = [
  { id: "captacao-01", imovelId: "imovel-03", proprietarioId: "pessoa-05", responsavel: "Camila Nogueira", etapa: "avaliacao", proximaAcao: "Validar parecer de mercado" },
  { id: "captacao-02", imovelId: "imovel-05", proprietarioId: "pessoa-01", responsavel: "Lívia Toledo", etapa: "documentacao", proximaAcao: "Receber matrícula atualizada" },
  { id: "captacao-03", imovelId: "imovel-09", proprietarioId: "pessoa-07", responsavel: "Renato Martins", etapa: "fotografia", proximaAcao: "Realizar ensaio na quinta-feira" },
  { id: "captacao-04", imovelId: "imovel-12", proprietarioId: "pessoa-03", responsavel: "Camila Nogueira", etapa: "publicacao", proximaAcao: "Revisar descrição e destaque" },
];
