import type { Metadata } from "next";
import { BarChart3, Camera, CheckCircle2, FileCheck2, Megaphone, ShieldCheck } from "lucide-react";
import { FormularioDemonstrativo } from "@/components/site/formulario-demonstrativo";

export const metadata: Metadata = { title: "Anuncie ou administre seu imóvel" };

const ETAPAS = [[BarChart3, "Avaliação", "Leitura de mercado e posicionamento do imóvel."], [FileCheck2, "Preparação", "Documentos, informações e estratégia comercial."], [Camera, "Apresentação", "Fotografia e anúncio com qualidade editorial."], [Megaphone, "Negociação", "Divulgação, atendimento e acompanhamento próximo."]] as const;

const VenderAlugarPage = () => <main><section className="bg-[#19191b] px-5 py-20 text-white sm:px-6 sm:py-28 lg:px-10"><div className="mx-auto max-w-[90rem]"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#e98291]">Seu patrimônio com a Perez</p><h1 className="mt-5 max-w-5xl text-5xl font-black leading-[1.04] tracking-[-0.055em] sm:text-7xl">Anuncie com estratégia. Administre com tranquilidade.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/60">Uma experiência completa para apresentar seu imóvel ao mercado e cuidar de toda a relação de locação.</p></div></section><section className="bg-[#f7f4ef] py-16 sm:py-24"><div className="mx-auto max-w-[90rem] px-5 sm:px-6 lg:px-10"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{ETAPAS.map(([Icone, titulo, texto], indice) => <article key={titulo} className="rounded-[1.35rem] border bg-white p-6"><span className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[#f6e7e9] text-[#b52235]"><Icone className="size-5" /></span><b className="text-4xl text-zinc-100">0{indice + 1}</b></span><h2 className="mt-8 text-xl font-black">{titulo}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{texto}</p></article>)}</div></div></section><section id="administracao" className="bg-white py-16 sm:py-24"><div className="mx-auto grid max-w-[90rem] gap-12 px-5 sm:px-6 lg:grid-cols-2 lg:px-10"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#b52235]">Administração de locação</p><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] sm:text-6xl">Seu imóvel cuidado de ponta a ponta.</h2><p className="mt-6 text-base leading-7 text-zinc-500">Do contrato à manutenção, a futura plataforma Perez conecta proprietário, locatário e equipe em uma única visão.</p><div className="mt-8 grid gap-3">{["Acompanhamento de contrato e reajustes", "Comunicação centralizada com o locatário", "Visão de repasses e documentos", "Solicitações de manutenção organizadas"].map((item) => <span key={item} className="flex items-center gap-3 text-sm font-semibold"><CheckCircle2 className="size-5 text-[#b52235]" /> {item}</span>)}</div><div className="mt-9 flex gap-3 rounded-2xl bg-zinc-950 p-5 text-white"><ShieldCheck className="size-6 shrink-0 text-[#e98291]" /><p className="text-sm leading-6 text-white/65"><b className="block text-white">Mais de 35 anos de experiência</b>Conhecimento local e cuidado com relações de longo prazo.</p></div></div><FormularioDemonstrativo titulo="Conte sobre seu imóvel" apoio="Simule a solicitação de uma avaliação comercial ou proposta de administração." acao="Solicitar avaliação demonstrativa" /></div></section></main>;

export default VenderAlugarPage;
