"use client";

import Link from "next/link";
import { ArrowRight, Map, Play, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { PASSOS_TOUR } from "@/lib/perez360/tour";

export const TourDemonstracao = ({ publico = false }: { publico?: boolean }) => <Dialog><DialogTrigger render={<Button variant={publico ? "default" : "outline"} size={publico ? "default" : "sm"} />}><Play className="size-3.5 fill-current" /> <span className={publico ? "" : "hidden lg:inline"}>Iniciar apresentação</span><span className={publico ? "hidden" : "lg:hidden"}>Tour</span></DialogTrigger><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><span className="mb-1 grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Map className="size-4" /></span><DialogTitle className="text-xl font-bold">Tour Perez 360</DialogTitle><DialogDescription>Oito módulos para apresentar o novo ecossistema em aproximadamente 10–15 minutos.</DialogDescription></DialogHeader><div className="grid gap-2 sm:grid-cols-2">{PASSOS_TOUR.map((passo) => <Link key={passo.href} href={passo.href} className="group flex items-center gap-3 rounded-xl border p-3 transition hover:border-primary/30 hover:bg-primary/[.03]"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-muted text-xs font-black text-primary">{passo.numero}</span><span className="min-w-0 flex-1"><b className="block text-xs">{passo.rotulo}</b><span className="text-[10px] text-muted-foreground">{passo.descricao}</span></span><ArrowRight className="size-3.5 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" /></Link>)}</div><div className="flex items-start gap-3 rounded-xl bg-violet-50 p-3 text-violet-800"><Sparkles className="mt-0.5 size-4 shrink-0" /><p className="text-[10px] leading-4"><b className="block">Apresentação visual</b>Todos os dados, integrações e operações financeiras são simulados.</p></div></DialogContent></Dialog>;
