"use client";

import { Clock3, RotateCcw, Settings2, ShieldCheck, UsersRound } from "lucide-react";
import { CabecalhoModulo } from "@/components/operacao/cabecalho-modulo";
import { AvisoDemonstracao } from "@/components/gestao/aviso-demonstracao";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";

const ConfiguracoesPage = () => <div className="h-full overflow-y-auto"><div className="mx-auto flex max-w-5xl flex-col gap-5 p-3 sm:p-5"><CabecalhoModulo sobrelinha="Preferências visuais" titulo="Configurações" descricao="Exemplo de setores, filas, horários e permissões da futura plataforma." icone={Settings2} acao={<Button variant="outline" onClick={() => window.location.reload()}><RotateCcw className="size-4" /> Restaurar exemplo</Button>} /><AvisoDemonstracao descricao="Os controles abaixo mudam apenas enquanto esta página está aberta." />{[{ titulo: "Setores e distribuição", apoio: "Regras visuais para direcionar cada atendimento.", icone: UsersRound, itens: [["Comercial", "Compra, venda, locação e lançamentos"], ["Administrativo", "Contratos, boletos, vistorias e manutenção"], ["Recepção", "Informações gerais e direcionamento"]] }, { titulo: "Horários e disponibilidade", apoio: "Exemplo de comportamento durante e fora do expediente.", icone: Clock3, itens: [["Atendimento em horário comercial", "Segunda a sexta, 8h às 18h"], ["Mensagem fora do expediente", "Confirma recebimento e informa retorno"], ["Distribuição automática", "Considera setor e disponibilidade"]] }, { titulo: "Segurança e papéis", apoio: "Controles que dependeriam de autenticação na produção.", icone: ShieldCheck, itens: [["Supervisores visualizam todas as filas", "Permissão demonstrativa"], ["Atendentes veem sua própria carteira", "Permissão demonstrativa"], ["Registro de alterações", "Histórico meramente visual"]] }].map(({ titulo, apoio, icone: Icone, itens }) => <section key={titulo} className="rounded-2xl border bg-background p-5 shadow-xs"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icone className="size-4" /></span><div><h2 className="text-sm font-bold">{titulo}</h2><p className="mt-1 text-[10px] text-muted-foreground">{apoio}</p></div></div><div className="mt-5 divide-y">{itens.map(([rotulo, descricao]) => <label key={rotulo} className="flex items-center gap-4 py-4"><span className="min-w-0 flex-1"><b className="block text-xs">{rotulo}</b><span className="text-[10px] text-muted-foreground">{descricao}</span></span><Switch defaultChecked aria-label={rotulo} /></label>)}</div><p className="mt-2 text-[9px] font-semibold uppercase tracking-[.1em] text-muted-foreground">Alterações somente nesta demonstração</p></section>)}</div></div>;
export default ConfiguracoesPage;
