"use client";

import { FormEvent, useState } from "react";
import { CalendarClock, Plus, UserRound, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { IMOVEIS_PEREZ, MANUTENCOES_PEREZ, PESSOAS_PEREZ } from "@/lib/perez360/dados";
import { agruparManutencoes } from "@/lib/perez360/operacao";
import type { ManutencaoPerez } from "@/lib/perez360/tipos";

const COLUNAS = [{ chave: "urgente", titulo: "Urgente", cor: "bg-red-500" }, { chave: "alta", titulo: "Alta prioridade", cor: "bg-amber-500" }, { chave: "normal", titulo: "Programadas", cor: "bg-blue-500" }, { chave: "concluida", titulo: "Concluídas", cor: "bg-emerald-500" }] as const;

export const QuadroManutencoes = () => {
  const [itens, setItens] = useState(MANUTENCOES_PEREZ);
  const grupos = agruparManutencoes(itens);
  const abrir = (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); const dados = new FormData(evento.currentTarget); const novo: ManutencaoPerez = { id: `local-${itens.length + 1}`, imovelId: String(dados.get("imovel")), solicitanteId: "pessoa-02", titulo: String(dados.get("titulo")), descricao: String(dados.get("descricao")), prioridade: "normal", status: "aberta", prestador: null, prazo: "2026-08-15" }; setItens((atuais) => [novo, ...atuais]); evento.currentTarget.reset(); };
  return <div><div className="mb-4 flex justify-end"><Dialog><DialogTrigger render={<Button />}><Plus className="size-4" /> Simular novo chamado</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo chamado demonstrativo</DialogTitle><DialogDescription>A solicitação será adicionada somente nesta tela.</DialogDescription></DialogHeader><form onSubmit={abrir} className="grid gap-4"><label className="grid gap-1 text-xs font-bold">Imóvel<select name="imovel" className="h-10 rounded-lg border bg-background px-3 text-sm">{IMOVEIS_PEREZ.filter((item) => item.finalidade === "locacao").map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.bairro}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Assunto<input required name="titulo" className="h-10 rounded-lg border px-3 text-sm" /></label><label className="grid gap-1 text-xs font-bold">Descrição<textarea required name="descricao" className="min-h-24 rounded-lg border p-3 text-sm" /></label><Button type="submit">Adicionar à demonstração</Button></form></DialogContent></Dialog></div><div className="scrollbar-hide flex gap-4 overflow-x-auto pb-2">{COLUNAS.map((coluna) => <section key={coluna.chave} className="w-[18rem] shrink-0 rounded-2xl bg-muted/60 p-3"><div className="flex items-center justify-between px-1 pb-3"><h2 className="flex items-center gap-2 text-xs font-bold"><span className={`size-2 rounded-full ${coluna.cor}`} />{coluna.titulo}</h2><span className="rounded-full bg-background px-2 py-1 text-[10px] font-bold text-muted-foreground">{grupos[coluna.chave].length}</span></div><div className="grid gap-2">{grupos[coluna.chave].map((item) => { const imovel = IMOVEIS_PEREZ.find((registro) => registro.id === item.imovelId)!; const solicitante = PESSOAS_PEREZ.find((registro) => registro.id === item.solicitanteId); return <article key={item.id} className="rounded-xl border bg-background p-4 shadow-xs"><span className="flex items-center justify-between text-[9px] font-bold uppercase tracking-[.1em] text-primary"><span>{imovel.codigo}</span><Wrench className="size-3" /></span><h3 className="mt-2 text-sm font-bold leading-5">{item.titulo}</h3><p className="mt-2 line-clamp-2 text-[11px] leading-4 text-muted-foreground">{item.descricao}</p><div className="mt-4 grid gap-2 border-t pt-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><UserRound className="size-3" /> {solicitante?.nome ?? "Solicitante da demonstração"}</span><span className="flex items-center gap-1.5"><CalendarClock className="size-3" /> Prazo {new Intl.DateTimeFormat("pt-BR").format(new Date(`${item.prazo}T12:00:00-03:00`))}</span><span className="font-semibold text-foreground">{item.prestador ?? "Aguardando prestador"}</span></div></article>; })}</div></section>)}</div></div>;
};
