import type { Metadata } from "next";
import { Building2, Clock3, MapPin, MessageCircle, Phone, Wrench } from "lucide-react";
import { FormularioDemonstrativo } from "@/components/site/formulario-demonstrativo";

export const metadata: Metadata = { title: "Contato" };

const ContatoPage = () => <main><section className="bg-[#19191b] px-5 py-20 text-white sm:px-6 sm:py-24 lg:px-10"><div className="mx-auto max-w-[90rem]"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#e98291]">Fale com a Perez</p><h1 className="mt-5 text-5xl font-black tracking-[-0.055em] sm:text-7xl">Como podemos ajudar?</h1><p className="mt-5 max-w-xl text-lg text-white/55">Escolha o caminho mais direto ou conte sua necessidade para a nossa equipe.</p></div></section><section className="bg-[#f7f4ef] py-16 sm:py-20"><div className="mx-auto max-w-[90rem] px-5 sm:px-6 lg:px-10"><div className="grid gap-4 lg:grid-cols-3">{[[Building2, "Comercial", "Compra, venda, locação e captação", "(43) 3377-7010"], [Wrench, "Administrativo", "Contratos, vistorias e manutenção", "(43) 3377-7020"], [MessageCircle, "Recepção", "Informações gerais e direcionamento", "(43) 3377-7000"]].map(([Icone, titulo, texto, telefone]) => <article key={String(titulo)} className="rounded-[1.35rem] border bg-white p-6"><span className="grid size-11 place-items-center rounded-xl bg-[#f6e7e9] text-[#b52235]"><Icone className="size-5" /></span><h2 className="mt-7 text-xl font-black">{String(titulo)}</h2><p className="mt-2 text-sm text-zinc-500">{String(texto)}</p><a href={`tel:${String(telefone).replace(/\D/g, "")}`} className="mt-6 flex items-center gap-2 text-sm font-bold text-[#b52235]"><Phone className="size-4" /> {String(telefone)}</a></article>)}</div></div></section><section className="bg-white py-16 sm:py-24"><div className="mx-auto grid max-w-[90rem] gap-10 px-5 sm:px-6 lg:grid-cols-2 lg:px-10"><div><h2 className="text-4xl font-black tracking-[-0.05em]">Visite a Perez em Londrina</h2><div className="mt-7 grid gap-4 text-sm text-zinc-600"><p className="flex gap-3"><MapPin className="size-5 shrink-0 text-[#b52235]" /> Avenida Higienópolis, Londrina — Paraná<br />Endereço demonstrativo para o protótipo.</p><p className="flex gap-3"><Clock3 className="size-5 shrink-0 text-[#b52235]" /> Segunda a sexta, das 8h às 18h<br />Sábado, das 8h às 12h.</p></div><div className="relative mt-8 min-h-72 overflow-hidden rounded-[1.5rem] bg-[#e8e3da]"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(32deg,transparent_46%,white_47%,white_52%,transparent_53%),linear-gradient(110deg,transparent_45%,white_46%,white_51%,transparent_52%)] [background-size:140px_120px]" /><span className="absolute left-1/2 top-1/2 grid size-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-[#b52235] text-white shadow-xl"><MapPin className="size-6" /></span><span className="absolute bottom-4 left-4 rounded-full bg-white/90 px-3 py-2 text-[0.65rem] font-bold text-zinc-500">Mapa ilustrativo — sem geolocalização real</span></div></div><FormularioDemonstrativo titulo="Conte o que você precisa" apoio="Sua mensagem será apresentada como uma simulação de entrada na Central Perez." acao="Simular atendimento" /></div></section></main>;

export default ContatoPage;
