import { CircleDollarSign, FileText, LockKeyhole } from "lucide-react";
import { CabecalhoModulo } from "@/components/operacao/cabecalho-modulo";
import { AvisoDemonstracao } from "@/components/gestao/aviso-demonstracao";
import { ResumoFinanceiro } from "@/components/gestao/resumo-financeiro";
import { Button } from "@/components/ui/button";
import { LANCAMENTOS_PEREZ } from "@/lib/perez360/dados";
import { calcularResumoFinanceiro } from "@/lib/perez360/indicadores";
import { formatarMoeda } from "@/lib/perez360/seletores";

const STATUS = { previsto: "Previsto", realizado: "Realizado", pendente: "Pendente" } as const;

const FinanceiroPage = () => { const resumo = calcularResumoFinanceiro(LANCAMENTOS_PEREZ); const maximo = Math.max(...LANCAMENTOS_PEREZ.map((item) => item.valor)); return <div className="h-full overflow-y-auto"><div className="mx-auto flex max-w-7xl flex-col gap-5 p-3 sm:p-5"><CabecalhoModulo sobrelinha="Módulo visual adicional" titulo="Resumo financeiro" descricao="Recebimentos, repasses e pendências apresentados sem emissão ou movimentação real." icone={CircleDollarSign} acao={<Button variant="outline"><FileText className="size-4" /> Simular relatório</Button>} /><AvisoDemonstracao titulo="Visão financeira demonstrativa" descricao="Não emite boletos, não consulta bancos, não concilia nem movimenta valores." /><ResumoFinanceiro resumo={resumo} /><div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border bg-background p-5 shadow-xs"><h2 className="text-sm font-bold">Fluxo do exemplo</h2><p className="mt-1 text-[10px] text-muted-foreground">Comparação visual dos lançamentos fictícios</p><div className="mt-6 grid gap-4">{LANCAMENTOS_PEREZ.map((item) => <div key={item.id} className="grid grid-cols-[7rem_1fr_auto] items-center gap-3"><span className="truncate text-[10px] font-semibold">{item.descricao}</span><span className="h-2 overflow-hidden rounded-full bg-muted"><span className={item.tipo === "recebimento" ? "block h-full rounded-full bg-primary" : "block h-full rounded-full bg-violet-500"} style={{ width: `${Math.round((item.valor / maximo) * 100)}%` }} /></span><b className="text-[10px]">{formatarMoeda(item.valor)}</b></div>)}</div></section><section className="overflow-hidden rounded-2xl border bg-background shadow-xs"><div className="border-b p-5"><h2 className="text-sm font-bold">Lançamentos do exemplo</h2></div><div className="divide-y">{LANCAMENTOS_PEREZ.map((item) => <div key={item.id} className="flex items-center gap-3 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted"><LockKeyhole className="size-3.5 text-muted-foreground" /></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{item.descricao}</b><span className="text-[10px] text-muted-foreground">{item.contratoId.toUpperCase()}</span></span><span className="text-right"><b className="block text-xs">{formatarMoeda(item.valor)}</b><span className="text-[9px] text-muted-foreground">{STATUS[item.status]}</span></span></div>)}</div></section></div></div></div>; };
export default FinanceiroPage;
